version: '2'
services:
    plex:
        container_name: plex
        extends:
            file: common.yml
            service: common
        image: "plexinc/pms-docker"
        ports:
            - "32400:32400/tcp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        volumes:
            - ./configs/plex:/config
            - ./volumes/plex/tv:/tv
            - ./volumes/plex/movies:/movies
            - ./volumes/plex/transcode:/transcode
    nzbget:
        container_name: nzbget
        extends:
            file: common.yml
            service: common
        expose:
            - "6789"
        image: "linuxserver/nzbget"
        volumes:
            - ./configs/nzbget:/config
            - ./volumes/nzbget:/downloads
    sonarr:
        container_name: sonarr
        extends:
            file: common.yml
            service: common
        expose:
            - "8989"
        image: "linuxserver/sonarr"
        volumes:
            - ./configs/sonarr:/config
            - ./volumes/nzbget:/downloads
            - ./volumes/plex/tv:/tv
    couchpotato:
        container_name: couchpotato
        extends:
            file: common.yml
            service: common
        expose:
            - "5050"
        image: "linuxserver/couchpotato"
        volumes:
            - ./configs/couchpotato:/config
            - ./volumes/nzbget:/downloads
            - ./volumes/plex/movies:/movies
    plexpy:
        container_name: plexpy
        extends:
            file: common.yml
            service: common
        expose:
            - "8181"
        image: "linuxserver/plexpy"
        volumes:
            - ./configs/plexpy:/config
            - ./volumes/plex/logs:/logs:ro
    transmission:
        container_name: transmission
        extends:
            file: common.yml
            service: common
        expose:
            - "9091"
        image: "linuxserver/transmission"
        ports:
            - "51413:51413/tcp"
            - "51413:51413/udp"
        volumes:
            - ./configs/transmission:/config
            - ./volumes/transmission:/downloads
    netdata:
        container_name: netdata
        cap_add:
            - SYS_PTRACE
        extends:
            file: common.yml
            service: common
        expose:
            - "19999"
        image: "titpetric/netdata"
        volumes:
            - ./configs/netdata:/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
    dockerui:
        container_name: dockerui
        extends:
            file: common.yml
            service: common
        expose:
            - "9000"
        image: "uifd/ui-for-docker"
        volumes:
            - ./configs/dockerui:/config
            - /var/run/docker.sock:/var/run/docker.sock
    hydra:
        container_name: hydra
        extends:
            file: common.yml
            service: common
        expose:
            - "5075"
        image: "linuxserver/hydra"
        volumes:
            - ./configs/hydra:/config
            - ./volumes/hydra:/downloads
    nginx:
        container_name: nginx
        extends:
            file: common.yml
            service: common
        image: "linuxserver/nginx"
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - ./configs/nginx:/config
