version: '3'
services:
    plex:
        # https://github.com/plexinc/pms-docker
        # https://hub.docker.com/r/plexinc/pms-docker/
        container_name: plex
        restart: unless-stopped
        expose:
            - "32400"
        image: "plexinc/pms-docker:plexpass"
        volumes:
            - ./volumes/plex/config:/config
            - ./volumes/plex/tv:/tv
            - ./volumes/plex/movies:/movies
            - ./volumes/plex/transcode:/transcode
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
            - ./plex.env
    nzbget:
        # https://github.com/linuxserver/docker-nzbget
        # https://hub.docker.com/r/linuxserver/nzbget/
        container_name: nzbget
        expose:
            - "6789"
        image: "linuxserver/nzbget"
        volumes:
            - ./volumes/nzbget/config:/config
            - ./volumes/nzbget/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
    sonarr:
        # https://github.com/linuxserver/docker-sonarr
        # https://hub.docker.com/r/linuxserver/sonarr/
        container_name: sonarr
        expose:
            - "8989"
        image: "linuxserver/sonarr"
        volumes:
            - ./volumes/sonarr/config:/config
            - ./volumes/nzbget/downloads:/downloads
            - ./volumes/transmission/downloads:/transmission
            - ./volumes/plex/tv:/tv
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
        depends_on:
            - nzbget
    radarr:
        # https://github.com/linuxserver/docker-radarr
        # https://hub.docker.com/r/linuxserver/radarr/
        container_name: radarr
        expose:
            - "7878"
        image: "linuxserver/radarr"
        volumes:
            - ./volumes/radarr/config:/config
            - ./volumes/nzbget/downloads:/downloads
            - ./volumes/transmission/downloads:/transmission
            - ./volumes/plex/movies:/movies
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
        depends_on:
            - nzbget
    plexpy:
        # https://github.com/linuxserver/docker-plexpy
        # https://hub.docker.com/r/linuxserver/plexpy/
        container_name: plexpy
        expose:
            - "8181"
        image: "linuxserver/plexpy"
        volumes:
            - ./volumes/plexpy/config:/config
            - ./volumes/plex/config/Library/Application Support/Plex Media Server/Logs:/logs:ro
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
        depends_on:
            - plex
    transmission:
        # https://github.com/linuxserver/docker-transmission
        # https://hub.docker.com/r/linuxserver/transmission/
        container_name: transmission
        expose:
            - "9091"
        image: "linuxserver/transmission"
        ports:
            - "51413:51413/tcp"
            - "51413:51413/udp"
        volumes:
            - ./volumes/transmission/config:/config
            - ./volumes/transmission/downloads:/downloads
            - ./volumes/transmission/watch:/watch
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
    portainer:
        # https://github.com/portainer/portainer
        # https://hub.docker.com/r/portainer/portainer/
        container_name: portainer
        expose:
            - "9000"
        image: "portainer/portainer"
        volumes:
            - ./volumes/portainer/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
    hydra:
        # https://github.com/linuxserver/docker-hydra
        # https://hub.docker.com/r/linuxserver/hydra/
        container_name: hydra
        expose:
            - "5075"
        image: "linuxserver/hydra"
        volumes:
            - ./volumes/hydra/config:/config
            - ./volumes/hydra/downloads:/downloads
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        env_file:
            - ./common.env
        restart: unless-stopped
    letsencrypt:
        # https://github.com/linuxserver/docker-letsencrypt
        # https://hub.docker.com/r/linuxserver/letsencrypt/
        container_name: letsencrypt
        env_file:
            - ./common.env
            - ./letsencrypt.env
        image: "linuxserver/letsencrypt"
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        privileged: true
        volumes:
            - ./volumes/letsencrypt/config:/config
            - /etc/localtime:/etc/localtime:ro
            - /dev/rtc:/dev/rtc:ro
        restart: unless-stopped
        depends_on:
            - plex
            - nzbget
            - sonarr
            - radarr
            - plexpy
            - transmission
            - portainer
            - hydra
