version: '3.7'
services:

    # https://hub.docker.com/r/linuxserver/plex/
    plex:
        container_name: plex
        image: linuxserver/plex
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
            VERSION: 'latest'
        networks:
            - traefik
        ports:
            - '32400:32400/tcp'
        volumes:
            - '${CONF_DIR}/plex:/config'
            - '${DATA_DIR}:/downloads'
            - '/tmp:/tmp'
        labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.plex.entrypoints: https
            traefik.http.routers.plex.tls.certresolver: cloudflare
            traefik.http.routers.plex.service: plex
            traefik.http.routers.plex.rule: Host(`plex.${CF_DOMAIN}`,`${CF_DOMAIN}`)
            traefik.http.services.plex.loadbalancer.server.port: 32400
            traefik.http.services.plex.loadbalancer.server.scheme: http
            traefik.http.services.plex.loadbalancer.passhostheader: true

    # https://hub.docker.com/r/linuxserver/nzbget/
    nzbget:
        container_name: nzbget
        image: linuxserver/nzbget
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONF_DIR}/nzbget:/config'
            - '${DATA_DIR}:/downloads'
        labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.nzbget.entrypoints: https
            traefik.http.routers.nzbget.tls.certresolver: cloudflare
            traefik.http.routers.nzbget.service: nzbget
            traefik.http.routers.nzbget.rule: Host(`nzbget.${CF_DOMAIN}`)
            traefik.http.services.nzbget.loadbalancer.server.port: 6789
            traefik.http.services.nzbget.loadbalancer.server.scheme: http
            traefik.http.services.nzbget.loadbalancer.passhostheader: true

    # https://hub.docker.com/r/linuxserver/sonarr/
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONF_DIR}/sonarr:/config'
            - '${DATA_DIR}:/downloads'
        labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.sonarr.entrypoints: https
            traefik.http.routers.sonarr.tls.certresolver: cloudflare
            traefik.http.routers.sonarr.service: sonarr
            traefik.http.routers.sonarr.rule: Host(`sonarr.${CF_DOMAIN}`)
            traefik.http.services.sonarr.loadbalancer.server.port: 8989
            traefik.http.services.sonarr.loadbalancer.server.scheme: http
            traefik.http.services.sonarr.loadbalancer.passhostheader: true
        links:
            - hydra
            - nzbget

    # https://hub.docker.com/r/linuxserver/radarr/
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONF_DIR}/radarr:/config'
            - '${DATA_DIR}:/downloads'
        labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.radarr.entrypoints: https
            traefik.http.routers.radarr.tls.certresolver: cloudflare
            traefik.http.routers.radarr.service: radarr
            traefik.http.routers.radarr.rule: Host(`radarr.${CF_DOMAIN}`)
            traefik.http.services.radarr.loadbalancer.server.port: 7878
            traefik.http.services.radarr.loadbalancer.server.scheme: http
            traefik.http.services.radarr.loadbalancer.passhostheader: true
        links:
            - hydra
            - nzbget

    # https://hub.docker.com/r/linuxserver/hydra2/
    hydra:
        container_name: hydra
        image: linuxserver/hydra2
        restart: unless-stopped
        environment:
            PUID: '${PUID}'
            PGID: '${PGID}'
            TZ: '${TZ}'
        networks:
            - traefik
        volumes:
            - '${CONF_DIR}/hydra:/config'
            - '${DATA_DIR}:/downloads'
        labels:
            traefik.enable: true
            traefik.docker.network: traefik
            traefik.http.routers.hydra.entrypoints: https
            traefik.http.routers.hydra.tls.certresolver: cloudflare
            traefik.http.routers.hydra.service: hydra
            traefik.http.routers.hydra.rule: Host(`hydra.${CF_DOMAIN}`)
            traefik.http.services.hydra.loadbalancer.server.port: 5076
            traefik.http.services.hydra.loadbalancer.server.scheme: http
            traefik.http.services.hydra.loadbalancer.passhostheader: true

    # https://hub.docker.com/_/traefik/
    traefik:
        container_name: traefik
        image: traefik:2.0.0
        restart: unless-stopped
        environment:
            TZ: '${TZ}'
            CF_API_EMAIL: '${CF_API_EMAIL}'
            CF_API_KEY: '${CF_API_KEY}'
        networks:
            - traefik
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - '${CONF_DIR}/traefik:/etc/traefik:rw'
        command:
            - "--log.level=INFO"
            - "--global.sendanonymoususage=false"
            - "--entrypoints.http.address=:80"
            - "--entrypoints.https.address=:443"
            - "--providers.docker=true"
            - "--providers.docker.exposedbydefault=false"
            - "--certificatesresolvers.cloudflare.acme.dnschallenge=true"
            - "--certificatesresolvers.cloudflare.acme.dnschallenge.provider=cloudflare"
            - "--certificatesresolvers.cloudflare.acme.storage=/etc/traefik/acme.json"
            - "--certificatesresolvers.cloudflare.acme.email=${CF_API_EMAIL}"
            # - "--certificatesresolvers.cloudflare.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"

networks:
    traefik:
        name: traefik
        attachable: true