version: '3'
services:

    # https://hub.docker.com/r/linuxserver/plex/
    plex:
        container_name: plex
        image: linuxserver/plex
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
            - 'VERSION=latest'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:plex.exampledomain.com'
            - 'traefik.port=32400'
            - 'traefik.protocol=http'
        volumes:
            - './data/plex/config:/config'
            - './data/plex/media/tv:/tv'
            - './data/plex/media/movies:/movies'
            - '/tmp:/transcode'

    # https://hub.docker.com/r/linuxserver/nzbget/
    nzbget:
        container_name: nzbget
        image: linuxserver/nzbget
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:nzbget.exampledomain.com'
            - 'traefik.port=6789'
            - 'traefik.protocol=http'
        volumes:
            - './data/nzbget/config:/config'
            - './data/nzbget/downloads:/downloads'

    # https://hub.docker.com/r/linuxserver/sonarr/
    sonarr:
        container_name: sonarr
        image: linuxserver/sonarr
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:sonarr.exampledomain.com'
            - 'traefik.port=8989'
            - 'traefik.protocol=http'
        volumes:
            - './data/sonarr/config:/config'
            - './data/nzbget/downloads:/downloads'
            - './data/plex/media/tv:/tv'

    # https://hub.docker.com/r/linuxserver/radarr/
    radarr:
        container_name: radarr
        image: linuxserver/radarr
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:radarr.exampledomain.com'
            - 'traefik.port=7878'
            - 'traefik.protocol=http'
        volumes:
            - './data/radarr/config:/config'
            - './data/nzbget/downloads:/downloads'
            - './data/plex/media/movies:/movies'

    # https://hub.docker.com/r/linuxserver/hydra2/
    hydra:
        container_name: hydra
        image: linuxserver/hydra2
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:hydra.exampledomain.com'
            - 'traefik.port=5076'
            - 'traefik.protocol=http'
        volumes:
            - './data/hydra/config:/config'
            - './data/hydra/downloads:/downloads'

    # https://hub.docker.com/r/linuxserver/duplicati/
    duplicati:
        container_name: duplicati
        image: linuxserver/duplicati
        restart: unless-stopped
        environment:
            - 'PUID=1000'
            - 'PGID=1000'
            - 'TZ=America/New_York'
        labels:
            - 'traefik.enable=true'
            - 'traefik.frontend.rule=Host:duplicati.exampledomain.com'
            - 'traefik.port=8200'
            - 'traefik.protocol=http'
        volumes:
            - './data/duplicati/config:/config'
            - '/:/source:ro'
        entrypoint: ['/bin/bash', '-c', 'sed -i "s/config/config --webservice-allowed-hostnames=*/" /etc/services.d/duplicati/run; /init']
    
    # https://hub.docker.com/_/traefik/
    traefik:
        container_name: traefik
        image: traefik
        restart: unless-stopped
        environment:
            - 'CF_API_EMAIL=example@address.com'
            - 'CF_API_KEY='
        ports:
            - '80:80/tcp'
            - '443:443/tcp'
        volumes:
            - '/var/run/docker.sock:/var/run/docker.sock:ro'
            - './traefik.toml:/etc/traefik/traefik.toml'
            - 'traefik_acme:/etc/traefik/acme.json'

volumes:
    traefik_acme:

