version: '2'
services:
    plex:
        container_name: plex
        extends:
            file: common.yml
            service: common
        image: "plexinc/pms-docker"
        ports:
            - "32400:32400/tcp"
            - "3005:3005/tcp"
            - "8324:8324/tcp"
            - "32469:32469/tcp"
            - "1900:1900/udp"
            - "32410:32410/udp"
            - "32412:32412/udp"
            - "32413:32413/udp"
            - "32414:32414/udp"
        volumes:
            - ./volumes/plex/config:/config
            - ./volumes/plex/tv:/tv
            - ./volumes/plex/movies:/movies
            - ./volumes/plex/transcode:/transcode
    nzbget:
        container_name: nzbget
        extends:
            file: common.yml
            service: common
        expose:
            - "6789"
        image: "linuxserver/nzbget"
        volumes:
            - ./volumes/nzbget/config:/config
            - ./volumes/nzbget/downloads:/downloads
    sonarr:
        container_name: sonarr
        extends:
            file: common.yml
            service: common
        expose:
            - "8989"
        image: "linuxserver/sonarr"
        volumes:
            - ./volumes/sonarr/config:/config
            - ./volumes/nzbget/downloads:/downloads
            - ./volumes/transmission/downloads:/transmission
            - ./volumes/plex/tv:/tv
    couchpotato:
        container_name: couchpotato
        extends:
            file: common.yml
            service: common
        expose:
            - "5050"
        image: "linuxserver/couchpotato"
        volumes:
            - ./volumes/couchpotato/config:/config
            - ./volumes/nzbget/downloads:/downloads
            - ./volumes/transmission/downloads:/transmission
            - ./volumes/plex/movies:/movies
    plexpy:
        container_name: plexpy
        extends:
            file: common.yml
            service: common
        expose:
            - "8181"
        image: "linuxserver/plexpy"
        volumes:
            - ./volumes/plexpy/config:/config
            - ./volumes/plex/config/logs:/logs:ro
    transmission:
        container_name: transmission
        extends:
            file: common.yml
            service: common
        expose:
            - "9091"
        image: "linuxserver/transmission"
        ports:
            - "51413:51413/tcp"
            - "51413:51413/udp"
        volumes:
            - ./volumes/transmission/config:/config
            - ./volumes/transmission/downloads:/downloads
            - ./volumes/transmission/watch:/watch
    netdata:
        container_name: netdata
        cap_add:
            - SYS_PTRACE
        extends:
            file: common.yml
            service: common
        expose:
            - "19999"
        image: "titpetric/netdata"
        volumes:
            - ./volumes/netdata/config:/config
            - /var/run/docker.sock:/var/run/docker.sock
            - /proc:/host/proc:ro
            - /sys:/host/sys:ro
    portainer:
        container_name: portainer
        extends:
            file: common.yml
            service: common
        expose:
            - "9000"
        image: "portainer/portainer"
        volumes:
            - ./volumes/portainer/data:/data
            - /var/run/docker.sock:/var/run/docker.sock
    hydra:
        container_name: hydra
        extends:
            file: common.yml
            service: common
        expose:
            - "5075"
        image: "linuxserver/hydra"
        volumes:
            - ./volumes/hydra/config:/config
            - ./volumes/hydra/downloads:/downloads
    nginx:
        container_name: nginx
        extends:
            file: common.yml
            service: common
        image: "nginx"
        ports:
            - "80:80/tcp"
            - "443:443/tcp"
        volumes:
            - ./volumes/nginx/config/conf.d:/etc/nginx/conf.d:ro
            - ./volumes/nginx/config/include.d:/etc/nginx/include.d:ro
            - ./volumes/nginx/config/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./volumes/nginx/keys:/keys:ro
            - ./volumes/nginx/logs:/logs
