version: '3'
services:

    # https://github.com/plexinc/pms-docker
    plex:
        image: 'plexinc/pms-docker:plexpass'
        restart: unless-stopped
        volumes:
            - './data/plex/config:/config'
            - './data/plex/media/tv:/tv'
            - './data/plex/media/movies:/movies'
            - '/tmp:/transcode'
        env_file:
            - './plex.env'
            - './common.env'

    # https://github.com/linuxserver/docker-nzbget
    # https://hub.docker.com/r/linuxserver/nzbget/
    nzbget:
        image: 'linuxserver/nzbget'
        restart: unless-stopped
        volumes:
            - './data/nzbget/config:/config'
            - './data/nzbget/downloads:/downloads'
        env_file:
            - './common.env'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:6789/']

    # https://github.com/linuxserver/docker-sonarr
    # https://hub.docker.com/r/linuxserver/sonarr/
    sonarr:
        image: 'linuxserver/sonarr'
        restart: unless-stopped
        volumes:
            - './data/sonarr/config:/config'
            - './data/nzbget/downloads:/downloads'
            - './data/plex/media/tv:/tv'
        env_file:
            - './common.env'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:8989/']

    # https://github.com/linuxserver/docker-radarr
    # https://hub.docker.com/r/linuxserver/radarr/
    radarr:
        image: 'linuxserver/radarr'
        restart: unless-stopped
        volumes:
            - './data/radarr/config:/config'
            - './data/nzbget/downloads:/downloads'
            - './data/plex/media/movies:/movies'
        env_file:
            - './common.env'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:7878/']

    # https://github.com/linuxserver/docker-hydra2
    # https://hub.docker.com/r/linuxserver/hydra2/
    hydra:
        image: 'linuxserver/hydra2'
        restart: unless-stopped
        volumes:
            - './data/hydra/config:/config'
            - './data/hydra/downloads:/downloads'
        env_file:
            - './common.env'
        healthcheck:
            test: ['CMD', 'curl', '-f', 'http://localhost:5076/']

    # https://github.com/abiosoft/caddy-docker
    caddy:
        build:
            context: 'github.com/abiosoft/caddy-docker.git'
            args:
                plugins: 'git,cors,realip,expires,cache,cloudflare,reauth'
        env_file:
            - './common.env'
            - './caddy.env'
        restart: unless-stopped
        volumes:
            - './Caddyfile:/etc/Caddyfile'
            - 'caddy_certs_vol:/root/.caddy'
            - '/etc/localtime:/etc/localtime:ro'
        ports:
            - '80:80/tcp'
            - '443:443/tcp'

volumes:
    caddy_certs_vol:

