
debug = false

logLevel = "DEBUG"
defaultEntryPoints = ["https","http"]

[entryPoints]
[entryPoints.http]
address = ":80"
[entryPoints.http.redirect]
entryPoint = "https"
[entryPoints.https]
address = ":443"
[entryPoints.https.tls]

[retry]

# [api]

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "klutchell.com"
watch = true
exposedByDefault = false

[acme]
email = "kylemharding@gmail.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
# caServer = "https://acme-staging-v02.api.letsencrypt.org/directory"
[acme.dnsChallenge]
provider = "cloudflare"
delayBeforeCheck = 0

